/**
 * Technical catalog constants.
 */

export const CATALOG_TYPE_LABELS = {
  symptom: "Síntomas",
  diagnostic: "Diagnósticos",
  procedure: "Procedimientos",
  material: "Materiales",
  recommendation: "Recomendaciones",
  service: "Servicios",
};

export const CATALOG_TECHNICAL_TYPES = [
  "symptom",
  "diagnostic",
  "procedure",
  "material",
  "recommendation",
];

export const BASE_SERVICE_CATALOG = [
  {
    type: "symptom",
    name: "Lentitud general",
    description: "El equipo responde lentamente en tareas comunes.",
    defaultPrice: 0,
    priceInformal: 0,
    priceFormal: 0,
    active: true,
    sortOrder: 1,
  },
  {
    type: "symptom",
    name: "Sobrecalentamiento leve",
    description: "El equipo presenta aumento de temperatura durante uso normal.",
    defaultPrice: 0,
    priceInformal: 0,
    priceFormal: 0,
    active: true,
    sortOrder: 2,
  },
  {
    type: "symptom",
    name: "No enciende",
    description: "El equipo no muestra encendido al presionar el botón de encendido.",
    defaultPrice: 0,
    priceInformal: 0,
    priceFormal: 0,
    active: true,
    sortOrder: 3,
  },
  {
    type: "diagnostic",
    name: "Acumulación de suciedad interna",
    description: "Presencia de polvo o residuos que afectan funcionamiento o temperatura.",
    defaultPrice: 0,
    priceInformal: 0,
    priceFormal: 0,
    active: true,
    sortOrder: 10,
  },
  {
    type: "diagnostic",
    name: "Pasta térmica reseca",
    description: "La pasta térmica ha perdido propiedades y requiere reemplazo.",
    defaultPrice: 0,
    priceInformal: 0,
    priceFormal: 0,
    active: true,
    sortOrder: 11,
  },
  {
    type: "diagnostic",
    name: "Sistema con bajo rendimiento",
    description: "Rendimiento inferior al esperado por saturación, temperatura o software.",
    defaultPrice: 0,
    priceInformal: 0,
    priceFormal: 0,
    active: true,
    sortOrder: 12,
  },
  {
    type: "procedure",
    name: "Limpieza interna",
    description: "Desarme parcial o completo para limpieza técnica interna.",
    defaultPrice: 10000,
    priceInformal: 10000,
    priceFormal: 15000,
    active: true,
    sortOrder: 20,
  },
  {
    type: "procedure",
    name: "Cambio de pasta térmica",
    description: "Retiro de pasta anterior y aplicación de nueva pasta térmica.",
    defaultPrice: 12000,
    priceInformal: 12000,
    priceFormal: 18000,
    active: true,
    sortOrder: 21,
  },
  {
    type: "procedure",
    name: "Optimización del sistema",
    description: "Ajustes de software, limpieza lógica y mejora de rendimiento.",
    defaultPrice: 12000,
    priceInformal: 12000,
    priceFormal: 18000,
    active: true,
    sortOrder: 22,
  },
  {
    type: "procedure",
    name: "Pruebas de funcionamiento",
    description: "Validación de temperatura, estabilidad y funcionamiento general.",
    defaultPrice: 5000,
    priceInformal: 5000,
    priceFormal: 8000,
    active: true,
    sortOrder: 23,
  },
  {
    type: "procedure",
    name: "Respaldo básico de datos",
    description: "Respaldo de archivos importantes antes o después del servicio técnico.",
    defaultPrice: 10000,
    priceInformal: 10000,
    priceFormal: 18000,
    active: true,
    sortOrder: 24,
  },
  {
    type: "procedure",
    name: "Instalación de sistema operativo y drivers",
    description: "Instalación limpia del sistema y configuración inicial de drivers.",
    defaultPrice: 18000,
    priceInformal: 18000,
    priceFormal: 25000,
    active: true,
    sortOrder: 25,
  },
  {
    type: "procedure",
    name: "Instalación de SSD o RAM",
    description: "Instalación física y validación de upgrade de hardware.",
    defaultPrice: 12000,
    priceInformal: 12000,
    priceFormal: 18000,
    active: true,
    sortOrder: 26,
  },
  {
    type: "procedure",
    name: "Cambio de teclado laptop",
    description: "Desmontaje e instalación de teclado de reemplazo.",
    defaultPrice: 18000,
    priceInformal: 18000,
    priceFormal: 25000,
    active: true,
    sortOrder: 27,
  },
  {
    type: "procedure",
    name: "Revisión de cargador, puertos y energía",
    description: "Inspección funcional de energía, carga y conectividad física.",
    defaultPrice: 10000,
    priceInformal: 10000,
    priceFormal: 15000,
    active: true,
    sortOrder: 28,
  },
  {
    type: "material",
    name: "Alcohol isopropílico",
    description: "Material utilizado para limpieza técnica.",
    defaultPrice: 3000,
    priceInformal: 3000,
    priceFormal: 3000,
    active: true,
    sortOrder: 30,
  },
  {
    type: "material",
    name: "Brocha antiestática",
    description: "Herramienta o insumo utilizado para limpieza interna delicada.",
    defaultPrice: 1500,
    priceInformal: 1500,
    priceFormal: 1500,
    active: true,
    sortOrder: 31,
  },
  {
    type: "material",
    name: "Pasta térmica",
    description: "Consumible para mejorar transferencia térmica.",
    defaultPrice: 5000,
    priceInformal: 5000,
    priceFormal: 5000,
    active: true,
    sortOrder: 32,
  },
  {
    type: "material",
    name: "SSD SATA 480GB",
    description: "Unidad de estado sólido para mejora de rendimiento.",
    defaultPrice: 45000,
    priceInformal: 45000,
    priceFormal: 48000,
    active: true,
    sortOrder: 33,
  },
  {
    type: "material",
    name: "RAM DDR4 8GB",
    description: "Módulo de memoria para upgrade de equipo compatible.",
    defaultPrice: 38000,
    priceInformal: 38000,
    priceFormal: 42000,
    active: true,
    sortOrder: 34,
  },
  {
    type: "material",
    name: "Cargador laptop compatible",
    description: "Cargador de reemplazo compatible para laptop.",
    defaultPrice: 28000,
    priceInformal: 28000,
    priceFormal: 32000,
    active: true,
    sortOrder: 35,
  },
  {
    type: "material",
    name: "Teclado de reemplazo laptop",
    description: "Repuesto de teclado compatible para laptop.",
    defaultPrice: 40000,
    priceInformal: 40000,
    priceFormal: 45000,
    active: true,
    sortOrder: 36,
  },
  {
    type: "recommendation",
    name: "Realizar mantenimiento cada 6 meses",
    description: "Se recomienda mantenimiento preventivo semestral.",
    defaultPrice: 0,
    priceInformal: 0,
    priceFormal: 0,
    active: true,
    sortOrder: 40,
  },
  {
    type: "recommendation",
    name: "Evitar obstrucción de ventilación",
    description: "Mantener libres las rejillas y salidas de aire.",
    defaultPrice: 0,
    priceInformal: 0,
    priceFormal: 0,
    active: true,
    sortOrder: 41,
  },
  {
    type: "recommendation",
    name: "Evitar uso en ambientes con polvo",
    description: "Reducir exposición a suciedad para evitar ingreso interno.",
    defaultPrice: 0,
    priceInformal: 0,
    priceFormal: 0,
    active: true,
    sortOrder: 42,
  },
  {
    type: "service",
    name: "Diagnóstico básico",
    description: "Diagnóstico general sin desarme complejo.",
    defaultPrice: 10000,
    priceInformal: 10000,
    priceFormal: 15000,
    active: true,
    sortOrder: 50,
  },
  {
    type: "service",
    name: "Diagnóstico con desarme parcial",
    description: "Diagnóstico técnico que requiere apertura parcial del equipo.",
    defaultPrice: 15000,
    priceInformal: 15000,
    priceFormal: 22000,
    active: true,
    sortOrder: 51,
  },
  {
    type: "service",
    name: "Mantenimiento preventivo laptop",
    description: "Servicio general de limpieza, revisión y optimización para laptop.",
    defaultPrice: 22000,
    priceInformal: 22000,
    priceFormal: 32000,
    active: true,
    sortOrder: 52,
  },
  {
    type: "service",
    name: "Mantenimiento preventivo tablet",
    description: "Servicio general de limpieza y optimización para tablet.",
    defaultPrice: 18000,
    priceInformal: 18000,
    priceFormal: 26000,
    active: true,
    sortOrder: 53,
  },
  {
    type: "service",
    name: "Limpieza interna + cambio de pasta térmica laptop",
    description: "Servicio combinado de limpieza interna y renovación térmica.",
    defaultPrice: 25000,
    priceInformal: 25000,
    priceFormal: 35000,
    active: true,
    sortOrder: 54,
  },
  {
    type: "service",
    name: "Servicio express / prioridad",
    description: "Atención prioritaria o con tiempo de respuesta acelerado.",
    defaultPrice: 8000,
    priceInformal: 8000,
    priceFormal: 12000,
    active: true,
    sortOrder: 55,
  },
];